-- create database my_party_schema

CREATE TABLE person (
	person_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	person_creation timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	person_name varchar(255) NOT NULL,
	CONSTRAINT pk_person_person_id PRIMARY KEY (person_id)
);

CREATE TABLE party_type (
	party_type_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	party_type_description varchar(255) NOT NULL,
	CONSTRAINT pk_party_type_party_type_id PRIMARY KEY (party_type_id)
);

CREATE TABLE party_status (
	party_status_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	party_status_description varchar(255) NOT NULL,
	CONSTRAINT pk_party_status_party_status_id PRIMARY KEY (party_status_id)
);

CREATE TABLE invite_type (
	invite_type_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	invite_type_description varchar(255) NOT NULL,
	CONSTRAINT pk_invite_type_invite_type_id PRIMARY KEY (invite_type_id)
);

CREATE TABLE invite_status (
	invite_status_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	invite_status_description varchar(255) NOT NULL,
	CONSTRAINT pk_invite_status_invite_status_id PRIMARY KEY (invite_status_id)
);

CREATE TABLE party (
	party_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	party_creation timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	party_title varchar(255) NOT NULL,
	person_id int4 NOT NULL, -- party hoster
	party_status_id int4 NOT NULL DEFAULT 1,
	party_type_id int4 NOT NULL DEFAULT 1,
	CONSTRAINT pk_party_party_id PRIMARY KEY (party_id),
	CONSTRAINT fk_party_party_status FOREIGN KEY (party_status_id) REFERENCES party_status(party_status_id),
	CONSTRAINT fk_party_party_type FOREIGN KEY (party_type_id) REFERENCES party_type(party_type_id),
	CONSTRAINT fk_party_person FOREIGN KEY (person_id) REFERENCES person(person_id) ON DELETE CASCADE
);

CREATE TABLE invite (
	invite_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	party_id int4 NOT NULL,
	person_id int4 NOT NULL,
	invite_creation timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	invite_type_id int4 NOT NULL DEFAULT 1,
	invite_status_id int4 NOT NULL DEFAULT 1,
	CONSTRAINT pk_invite_invite_id PRIMARY KEY (invite_id),
	CONSTRAINT fk_invite_invite_status FOREIGN KEY (invite_status_id) REFERENCES invite_status(invite_status_id),
	CONSTRAINT fk_invite_invite_type FOREIGN KEY (invite_type_id) REFERENCES invite_type(invite_type_id),
	CONSTRAINT fk_invite_party FOREIGN KEY (party_id) REFERENCES party(party_id) ON DELETE CASCADE,
	CONSTRAINT fk_invite_person FOREIGN KEY (person_id) REFERENCES person(person_id) ON DELETE CASCADE
);
